import { GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import puppeteer from "puppeteer";
import {
  interviewReportSchema,
  mockInterviewAnswerEvaluationSchema,
  mockInterviewFinalReportSchema,
  mockInterviewQuestionSchema,
} from "../schema/zodSchema.js";

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

async function generateInterviewReport({
  resume,
  selfDescription,
  jobDescription,
}) {
  const prompt = `Generate an interview report for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}
`;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: zodToJsonSchema(interviewReportSchema),
    },
  });

  return JSON.parse(response.text);
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });

  const pdfBuffer = await page.pdf({
    format: "A4",
    margin: {
      top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm",
    },
  });

  await browser.close();

  return pdfBuffer;
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const resumePdfSchema = z.object({
    html: z
      .string()
      .describe(
        "The HTML content of the resume which can be converted to PDF using any library like puppeteer",
      ),
  });

  const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: zodToJsonSchema(resumePdfSchema),
    },
  });

  const jsonContent = JSON.parse(response.text);

  const pdfBuffer = await generatePdfFromHtml(jsonContent.html);

  return pdfBuffer;
}

function parseAiJsonResponse(response) {
  try {
    return JSON.parse(response.text);
  } catch (error) {
    throw new Error(`Failed to parse AI response: ${error.message}`);
  }
}

async function generateFirstMockInterviewQuestion({
  resume,
  selfDescription,
  jobDescription,
  skillGaps,
  title,
  matchScore,
  interviewType,
  difficulty,
}) {
  const prompt = `You are an expert interviewer conducting a mock interview for a candidate applying to the job "${title}".

                        Interview Type: ${interviewType}
                        Difficulty: ${difficulty}

                        Job Description:
                        ${jobDescription}

                        Candidate Resume:
                        ${resume}

                        Candidate Self Description:
                        ${selfDescription}

                        Candidate Skill Gaps:
                        ${JSON.stringify(skillGaps || [])}

                        Candidate Match Score: ${matchScore}

                        Generate the FIRST interview question for this mock interview. The question must:
                        - be tailored to the candidate's resume, the job description and the identified skill gaps
                        - target one of the candidate's weakest areas, especially a high severity skill gap
                        - be appropriate for a ${difficulty} difficulty ${interviewType} interview
                        - be self-contained and answerable by the candidate in 2-3 minutes

                        Return a JSON object containing the question, the intention of the interviewer behind asking it, and its category which can be "technical", "behavioral" or "mixed".
                    `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: zodToJsonSchema(mockInterviewQuestionSchema),
    },
  });

  return parseAiJsonResponse(response);
}

async function generateNextMockInterviewQuestion({
  resume,
  selfDescription,
  jobDescription,
  skillGaps,
  title,
  interviewType,
  difficulty,
  previousQuestion,
  previousAnswer,
  previousEvaluation,
  questionHistory,
}) {
  const prompt = `You are an expert interviewer conducting a mock interview for a candidate applying to the job "${title}".

                        Interview Type: ${interviewType}
                        Difficulty: ${difficulty}

                        Job Description:
                        ${jobDescription}

                        Candidate Resume:
                        ${resume}

                        Candidate Self Description:
                        ${selfDescription}

                        Candidate Skill Gaps:
                        ${JSON.stringify(skillGaps || [])}

                        Question just asked:
                        ${previousQuestion}

                        Candidate's answer:
                        ${previousAnswer}

                        Evaluation of that answer:
                        ${JSON.stringify(previousEvaluation)}

                        Questions already asked in this interview (do NOT repeat or closely resemble these):
                        ${JSON.stringify(questionHistory)}

                        Generate the NEXT interview question for this mock interview. The question must:
                        - adapt to the candidate's performance on the previous question, digging deeper into areas where they were weak and not spending too much time on areas where they were strong
                        - not repeat or closely resemble any of the already asked questions
                        - be appropriate for a ${difficulty} difficulty ${interviewType} interview
                        - be self-contained and answerable by the candidate in 2-3 minutes

                        Return a JSON object containing the question, the intention of the interviewer behind asking it, and its category which can be "technical", "behavioral" or "mixed".
                    `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: zodToJsonSchema(mockInterviewQuestionSchema),
    },
  });

  return parseAiJsonResponse(response);
}

async function evaluateMockInterviewAnswer({
  question,
  intention,
  answer,
  resume,
  selfDescription,
  jobDescription,
  interviewType,
  difficulty,
}) {
  const prompt = `You are an expert interviewer evaluating a candidate's answer during a ${interviewType} mock interview at ${difficulty} difficulty.

                        Question asked:
                        ${question}

                        Intention of the question:
                        ${intention}

                        Candidate's answer:
                        ${answer}

                        Candidate Resume:
                        ${resume}

                        Candidate Self Description:
                        ${selfDescription}

                        Job Description:
                        ${jobDescription}

                        Evaluate the candidate's answer on clarity, correctness, structure, depth and relevance to the question. Return a JSON object with:
                        - score: a number between 0 and 100
                        - strengths: an array of specific strengths in the candidate's answer
                        - weaknesses: an array of specific weaknesses or gaps in the candidate's answer
                        - feedback: concise and actionable feedback for the candidate
                        - idealAnswer: a model ideal answer the candidate should have given
                    `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: zodToJsonSchema(mockInterviewAnswerEvaluationSchema),
    },
  });

  return parseAiJsonResponse(response);
}

async function generateMockInterviewFinalReport({
  title,
  jobDescription,
  interviewType,
  difficulty,
  questionEvaluations,
}) {
  const prompt = `You are an expert interviewer who just finished conducting a ${interviewType} mock interview at ${difficulty} difficulty for the job "${title}".

                        Job Description:
                        ${jobDescription}

                        Here is the question-by-question performance of the candidate:
                        ${JSON.stringify(questionEvaluations)}

                        Generate a comprehensive final interview report for the candidate as a JSON object with:
                        - overallScore: a number between 0 and 100
                        - technicalScore: a number between 0 and 100
                        - communicationScore: a number between 0 and 100
                        - problemSolvingScore: a number between 0 and 100
                        - confidenceScore: a number between 0 and 100
                        - strengths: an array of strings summarizing the candidate's overall strengths
                        - weaknesses: an array of strings summarizing the candidate's overall weaknesses
                        - recommendations: an array of strings with actionable steps to improve before the real interview
                        - summary: a paragraph summarizing the overall performance of the candidate
                        - hiringReadiness: one of "low", "medium" or "high"
                    `;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: zodToJsonSchema(mockInterviewFinalReportSchema),
    },
  });

  return parseAiJsonResponse(response);
}

export {
  generateInterviewReport,
  generateResumePdf,
  generateFirstMockInterviewQuestion,
  generateNextMockInterviewQuestion,
  evaluateMockInterviewAnswer,
  generateMockInterviewFinalReport,
};
